# Generated by Django 2.1.15 on 2023-03-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.SmallIntegerField()),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('weight', models.SmallIntegerField(blank=True, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('chin', models.SmallIntegerField(blank=True, null=True)),
                ('run', models.CharField(blank=True, max_length=10, null=True)),
                ('abdominalcurl', models.SmallIntegerField(blank=True, db_column='AbdominalCurl', null=True)),
                ('jump', models.SmallIntegerField(blank=True, null=True)),
                ('starttrain', models.DateField(blank=True, db_column='StartTrain', null=True)),
                ('nexttest', models.DateField(blank=True, db_column='NextTest', null=True)),
                ('aerobic', models.SmallIntegerField(blank=True, db_column='Aerobic', null=True)),
                ('train_abdominalcurl', models.SmallIntegerField()),
                ('train_chin', models.SmallIntegerField()),
                ('train_jump', models.SmallIntegerField()),
                ('train_run', models.SmallIntegerField()),
                ('iscompliance', models.SmallIntegerField(blank=True, null=True)),
                ('chin_level', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
