# Generated by Django 2.1.15 on 2023-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecodTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete='cascade', to='user.Users')),
            ],
            options={
                'db_table': 'RecordTrain',
                'managed': True,
            },
        ),
    ]
