# Generated by Django 2.1.15 on 2023-03-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_recodtrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
