# Generated by Django 2.1.15 on 2023-03-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230325_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='grade',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
