# Generated by Django 2.1.15 on 2023-03-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_trainplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='TrainPlan',
        ),
    ]
