# Generated by Django 2.1.15 on 2023-03-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230326_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete='cascade', to='user.Users')),
            ],
            options={
                'db_table': 'TrainPlan',
                'managed': True,
            },
        ),
    ]
