# Generated by Django 2.1.15 on 2023-04-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_trainplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainplan',
            name='plan_date',
        ),
        migrations.RemoveField(
            model_name='trainplan',
            name='user',
        ),
        migrations.AddField(
            model_name='trainplan',
            name='day',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainplan',
            name='restTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainplan',
            name='trainContent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainplan',
            name='trainName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainplan',
            name='type',
            field=models.CharField(default='M-L', max_length=5),
        ),
        migrations.AddField(
            model_name='trainplan',
            name='week',
            field=models.SmallIntegerField(default=1),
        ),
    ]
