# Generated by Django 2.1.15 on 2023-04-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230421_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='strength',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
