# Generated by Django 2.1.15 on 2023-05-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20230430_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100)),
                ('trainTime', models.DateTimeField(auto_now=True)),
                ('day', models.SmallIntegerField(default=1)),
                ('trainName', models.CharField(blank=True, max_length=50, null=True)),
                ('trainTime1', models.SmallIntegerField(blank=True, null=True)),
                ('trainTime2', models.SmallIntegerField(blank=True, null=True)),
                ('trainTime3', models.SmallIntegerField(blank=True, null=True)),
                ('trainTime4', models.SmallIntegerField(blank=True, null=True)),
                ('restTime1', models.SmallIntegerField(blank=True, null=True)),
                ('restTime2', models.SmallIntegerField(blank=True, null=True)),
                ('restTime3', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
