# Generated by Django 2.1.15 on 2023-05-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20230502_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TFRecord',
            new_name='JXRecord',
        ),
    ]
