# Generated by Django 2.1.15 on 2023-05-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20230502_1727'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jxrecord',
            table='JXRecord',
        ),
    ]
