# Generated by Django 2.1.15 on 2023-05-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20230502_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='jxrecord',
            name='restTime4',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jxrecord',
            name='restTime5',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jxrecord',
            name='trainTime5',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jxrecord',
            name='trainTime6',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
