# Generated by Django 2.1.15 on 2023-05-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20230503_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='jxrecord',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
