# Generated by Django 2.1.15 on 2023-05-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_jxrecord_finish'),
    ]

    operations = [

        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
        ),

    ]
