# Generated by Django 2.1.15 on 2023-05-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20230510_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='openid',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
