# Generated by Django 2.1.15 on 2023-05-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_users_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='jxrecord',
            name='LongRunTime',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
