# Generated by Django 2.1.15 on 2023-05-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_jxrecord_lsdtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='jxrecord',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
