# Generated by Django 2.1.15 on 2023-05-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_jxrecord_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
